#!/bin/bash

SRC="${BASH_SOURCE[0]}"

see_lst_fun()
{
  mapfile -t fun_array < <( grep -e '^[a-z].*_.*(){' "$SRC"  | sed 's|(){.*||g' )
  mapfile -t dsc_array < <( grep -e '^##.*' "$SRC" | sed 's|^##.*::||g' )
  mapfile -t dsc_count < <( grep -c '^##.*' "$SRC" | sed 's|^##.*::||g' )
  echo -e ""
  echo -e "Useage: $SRC && <funtion name>"
  echo -e "Options:"
  
x=0
until [ "$x" -eq "${dsc_count[0]}" ];
do
   printf '\t%s\t%s \n' "${fun_array[$x]}" "${dsc_array[$x]}"
   (( x++ ))
done

}

help()
{
  echo -e ""
  echo -e "Useage: $SRC -h"
  echo -e "Options:"
  echo -e "\t-l\tList functions"
  echo -e "\t-h\tPrint this help."
  echo -e "\t-v\tPrint version info."
}

set_funName_01(){
##Discription::This is description set_funName_01
  printf '%s %s\n' " set_funtion_01 " " This is printf description"

}

get_funName_01(){
##Discription::This is description get_funName_01
  printf '%s %s\n' "get_funtion_01 " " This is printf description"

}

see_funName_01(){
##Discription::This is description see_funName_01
  printf '%s %s\n ' "see_funtion_01 " " This is printf description"

}

run_funName_01(){
##Discription::This is description run_funName_01
  printf '%s %s\n' "run_funtion_01 " " This is printf description"

}

set_funName_02(){
##Discription::This is description set_funName_02
  printf '%s %s\n' "set_funName_02 )" " This is printf description"

}

get_funName_02(){
##Discription::This is description get_funName_02
  printf '%s %s\n' "get_funName_02 " " This is printf description"

}

see_funName_02(){
##Discription::This is description see_funName_02
  printf '%s %s\n' "see_funName_02 " " This is printf description"

}

run_funName_02(){
##Discription::This is description run_funName_02
  printf '%s %s\n' "run_funName_02 " " This is printf description"

}

if [[ $# -eq 1 ]] ; then
while getopts ":hl" opt; do
    case $opt in
      h) help break ;;
      l) see_lst_fun break ;;
      ?) help break ;;
    esac
  exit
done

fi
